export const TASKS = [
  { label: 'Tarefa 01', route: 'Task01' },
  { label: 'Tarefa 02', route: 'Task02' },
  { label: 'Tarefa 03', route: 'Task03' },
  { label: 'Tarefa 04', route: 'Task04' },
  { label: 'Tarefa 05', route: 'Task05' },
  { label: 'Tarefa 06', route: 'Task06' },
  { label: 'Tarefa 07', route: 'Task07' },
  { label: 'Tarefa 08', route: 'Task08' },
  { label: 'Tarefa 09', route: 'Task09' },
  { label: 'Tarefa 10', route: 'Task10' },
  { label: 'Tarefa 11', route: 'Task11' },
  { label: 'Tarefa 12', route: 'Task12' },
  { label: 'Tarefa 13', route: 'Task13' },
  { label: 'Tarefa 14', route: 'Task14' },
  { label: 'Tarefa 15', route: 'Task15' },
  { label: 'Tarefa 16', route: 'Task16' },
];
